name: Nugget
version: 1.1.3
main:  com.chargnn.Main
depend: [Vault]
description: Another economy plugin
commands:
  balance:
    description: Command related to balances
    usage: /[set/add/sub] [player/amount]
  bank:
    description: Command related to banks
    usage: /[create/add/sub/remove] [player/bank name/amount]
permissions:
  ngt.balance:
    description: Use to see player's balances
  ngt.balance.other:
    description: Use to see other player's balances
    default: op
  ngt.balance.add:
    description: Add an amount of money to a player
    default: op
  ngt.balance.sub:
    description: Substract an amount of money from player
    default: op
  ngt.balance.set:
    description: Set an amount of money to a player
    default: op